name: Update tested plugins
on:
  push:
    branches: [ plugin_api_v2 ]
    paths:
      - 'plugins.json'
jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          token: ${{ secrets.UPDATER }}
          # otherwise, you will failed to push refs to dest repo
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run script
        run: python ./ci/src/update-tested.py
      - name: Update plugin manifest
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Tested plugins"
          push_options: --force
          branch: plugin_api_v2